---
  el:
    hosts:
      centos7:
        ansible_connection: local 
  deb:
    hosts:
      ubuntu:
        ansible_connection: local 
  local:
    hosts:
      local-host:
        ansible_connection: local